from enum import StrEnum


class DevotionErrorCode(StrEnum):
    DATE_NOT_SCHEDULED = "DATE_NOT_SCHEDULED"
    TRANSLATION_NOT_FOUND = "TRANSLATION_NOT_FOUND"
    DEVOTION_NOT_FOUND = "DEVOTION_NOT_FOUND"
    LOCALE_NOT_FOUND = "LOCALE_NOT_FOUND"
    TRANSLATIONS_INCOMPLETE = "TRANSLATIONS_INCOMPLETE"
    DEVOTION_SCHEDULED = "DEVOTION_SCHEDULED"
    LESSON_NOTE_DATE_NOT_TODAY = "LESSON_NOTE_DATE_NOT_TODAY"
    INVALID_TIME_ZONE = "INVALID_TIME_ZONE"


class DevotionStatus(StrEnum):
    DRAFT = "draft"
    READY = "ready"
