from enum import StrEnum


class DevotionErrorCode(StrEnum):
    DATE_NOT_SCHEDULED = "DATE_NOT_SCHEDULED"
    TRANSLATION_NOT_FOUND = "TRANSLATION_NOT_FOUND"
    DEVOTION_NOT_FOUND = "DEVOTION_NOT_FOUND"
    LOCALE_NOT_FOUND = "LOCALE_NOT_FOUND"
    TRANSLATIONS_INCOMPLETE = "TRANSLATIONS_INCOMPLETE"
    DEVOTION_SCHEDULED = "DEVOTION_SCHEDULED"
    DEVOTION_NOT_READY = "DEVOTION_NOT_READY"
    DAILY_LESSON_DATE_ALREADY_SCHEDULED = "DAILY_LESSON_DATE_ALREADY_SCHEDULED"
    DAILY_LESSON_DATE_IN_PAST = "DAILY_LESSON_DATE_IN_PAST"
    DAILY_LESSON_SCHEDULE_NOT_FOUND = "DAILY_LESSON_SCHEDULE_NOT_FOUND"
    INVALID_DAILY_LESSON_SCHEDULE_RANGE = "INVALID_DAILY_LESSON_SCHEDULE_RANGE"
    LESSON_NOTE_DATE_NOT_TODAY = "LESSON_NOTE_DATE_NOT_TODAY"
    INVALID_TIME_ZONE = "INVALID_TIME_ZONE"


class DevotionStatus(StrEnum):
    DRAFT = "draft"
    READY = "ready"
