from datetime import date
from typing import Protocol
from uuid import UUID

from portal.domain.devotion.constants import DevotionStatus
from portal.domain.devotion.entities import AnonymousDailyLesson, DailyLesson, Devotion, EncounterStreak, LessonNote
from portal.domain.locale.entities import Locale


class DevotionRepositoryPort(Protocol):
    async def fetch_daily_lesson(
        self, lesson_date: date, locale_id: UUID | None, locale_code: str | None, include_authored_sections: bool
    ) -> AnonymousDailyLesson | DailyLesson | None: ...

    async def daily_lesson_exists(self, lesson_date: date) -> bool: ...

    async def insert_encounter_day(self, user_id: UUID, encounter_date: date) -> bool: ...

    async def get_encounter_streak(self, user_id: UUID) -> EncounterStreak | None: ...

    async def save_encounter_streak(self, streak: EncounterStreak) -> None: ...

    async def list_recent_encounter_dates(self, user_id: UUID, through_date: date) -> list[date]: ...

    async def get_lesson_note(self, user_id: UUID, note_date: date) -> LessonNote | None: ...

    async def upsert_lesson_note(self, user_id: UUID, note: LessonNote) -> None: ...

    async def get_devotion(self, devotion_id: UUID) -> Devotion | None: ...

    async def insert_devotion(self, devotion_id: UUID, passage_start: str, passage_end: str) -> None: ...

    async def update_devotion(self, devotion_id: UUID, passage_start: str, passage_end: str) -> int: ...

    async def update_devotion_status(self, devotion_id: UUID, status: DevotionStatus) -> int: ...

    async def is_devotion_scheduled(self, devotion_id: UUID) -> bool: ...

    async def delete_devotion(self, devotion_id: UUID) -> int: ...

    async def resolve_locale(self, locale_code: str) -> Locale | None: ...

    async def list_active_locales(self) -> list[Locale]: ...

    async def list_translation_locale_ids(self, devotion_id: UUID) -> set[UUID]: ...

    async def upsert_translation(self, devotion_id: UUID, locale_id: UUID, reflect: list[str], apply: str, pray: str) -> None: ...

    async def fetch_devotion_pages(
        self, page: int, page_size: int, status: DevotionStatus | None, missing_locale_id: UUID | None
    ) -> tuple[list[Devotion], int]: ...
