"""replace verse content with nullable lines, search text, and verse end

Revision ID: 3a5fb35a2a70
Revises: 5ab9e424a1bd
Create Date: 2026-09-10 11:27:22.290001

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a5fb35a2a70'
down_revision: Union[str, Sequence[str], None] = '5ab9e424a1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verses', sa.Column('verse_end', sa.Integer(), nullable=True, comment='Merged verse end (YouVersion ev); null when unmerged'), schema='bible')
    op.add_column(
        'verses',
        sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured verse lines; null until read-time fill'),
        schema='bible',
    )
    op.add_column(
        'verses', sa.Column('search_text', sa.Text(), nullable=True, comment='Concatenated Scripture for later search; null until fill'), schema='bible'
    )
    op.alter_column(
        'verses', 'verse', existing_type=sa.INTEGER(), comment='Verse start number', existing_comment='Verse number', existing_nullable=False, schema='bible'
    )
    op.drop_column('verses', 'content', schema='bible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verses', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='Verse content (version-specific)'), schema='bible')
    op.alter_column(
        'verses', 'verse', existing_type=sa.INTEGER(), comment='Verse number', existing_comment='Verse start number', existing_nullable=False, schema='bible'
    )
    op.drop_column('verses', 'search_text', schema='bible')
    op.drop_column('verses', 'lines', schema='bible')
    op.drop_column('verses', 'verse_end', schema='bible')
    # ### end Alembic commands ###
