"""add bible version, book, and verse catalog

Revision ID: 7cbcd65af3e1
Revises: 801343331fc0
Create Date: 2026-09-05 19:50:21.784583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbcd65af3e1'
down_revision: Union[str, Sequence[str], None] = '801343331fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS bible")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('youversion_bible_id', sa.String(length=20), nullable=False, comment="YouVersion bible_id, e.g., '1392'"),
    sa.Column('abbreviation', sa.String(length=50), nullable=False, comment="English abbreviation, e.g., 'CCBT'"),
    sa.Column('title', sa.String(length=255), nullable=False, comment='English title'),
    sa.Column('localized_title', sa.String(length=255), nullable=False, comment='Localized title'),
    sa.Column('localized_abbreviation', sa.String(length=50), nullable=True, comment='Localized abbreviation'),
    sa.Column('language_tag', sa.String(length=20), nullable=False, comment="Language tag, e.g., 'zh-Hant-TW'"),
    sa.Column('copyright', sa.Text(), nullable=True, comment='Copyright information'),
    sa.Column('promotional_content', sa.Text(), nullable=True, comment='Promotional content'),
    sa.Column('publisher_url', sa.String(length=500), nullable=True, comment='Publisher URL'),
    sa.Column('youversion_deep_link', sa.String(length=500), nullable=True, comment='YouVersion deep link'),
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='Organization ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is version active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions')),
    schema='bible',
    comment='Bible versions table'
    )
    op.create_index(op.f('ix_versions_is_active'), 'versions', ['is_active'], unique=False, schema='bible')
    op.create_index(op.f('ix_versions_language_tag'), 'versions', ['language_tag'], unique=False, schema='bible')
    op.create_index(op.f('ix_versions_youversion_bible_id'), 'versions', ['youversion_bible_id'], unique=True, schema='bible')
    op.create_table('books',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('bible_version_id', sa.UUID(), nullable=False, comment='Bible version ID'),
    sa.Column('book_code', sa.String(length=10), nullable=False, comment="Book code, e.g., 'GEN', 'MAT'"),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Book title'),
    sa.Column('full_title', sa.String(length=100), nullable=True, comment='Full book title'),
    sa.Column('abbreviation', sa.String(length=10), nullable=True, comment='Book abbreviation'),
    sa.Column('canon', sa.String(length=20), nullable=False, comment="Canon type: 'old_testament' or 'new_testament'"),
    sa.Column('chapter_count', sa.Integer(), nullable=False, comment='Number of chapters in this book'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.ForeignKeyConstraint(['bible_version_id'], ['bible.versions.id'], name=op.f('fk_books_bible_version_id_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('bible_version_id', 'book_code', name=op.f('uq_books_bible_version_id_book_code')),
    schema='bible',
    comment='Bible books table - books belong to a specific version'
    )
    op.create_index(op.f('ix_books_bible_version_id'), 'books', ['bible_version_id'], unique=False, schema='bible')
    op.create_index(op.f('ix_books_book_code'), 'books', ['book_code'], unique=False, schema='bible')
    op.create_index(op.f('ix_books_canon'), 'books', ['canon'], unique=False, schema='bible')
    op.create_table('verses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('book_id', sa.UUID(), nullable=False, comment='Book ID (which also identifies the version)'),
    sa.Column('chapter', sa.Integer(), nullable=False, comment='Chapter number'),
    sa.Column('verse', sa.Integer(), nullable=False, comment='Verse number'),
    sa.Column('passage_id', sa.String(length=50), nullable=False, comment="Passage ID, e.g., 'GEN.1.1'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Verse content (version-specific)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['book_id'], ['bible.books.id'], name=op.f('fk_verses_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verses')),
    sa.UniqueConstraint('book_id', 'chapter', 'verse', name=op.f('uq_verses_book_id_chapter_verse')),
    sa.UniqueConstraint('book_id', 'passage_id', name=op.f('uq_verses_book_id_passage_id')),
    schema='bible',
    comment='Bible verses table - verse belongs to a book (which belongs to a version)'
    )
    op.create_index(op.f('ix_verses_book_id'), 'verses', ['book_id'], unique=False, schema='bible')
    op.create_index(op.f('ix_verses_chapter'), 'verses', ['chapter'], unique=False, schema='bible')
    op.create_index(op.f('ix_verses_passage_id'), 'verses', ['passage_id'], unique=False, schema='bible')
    op.create_index(op.f('ix_verses_verse'), 'verses', ['verse'], unique=False, schema='bible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verses_verse'), table_name='verses', schema='bible')
    op.drop_index(op.f('ix_verses_passage_id'), table_name='verses', schema='bible')
    op.drop_index(op.f('ix_verses_chapter'), table_name='verses', schema='bible')
    op.drop_index(op.f('ix_verses_book_id'), table_name='verses', schema='bible')
    op.drop_table('verses', schema='bible')
    op.drop_index(op.f('ix_books_canon'), table_name='books', schema='bible')
    op.drop_index(op.f('ix_books_book_code'), table_name='books', schema='bible')
    op.drop_index(op.f('ix_books_bible_version_id'), table_name='books', schema='bible')
    op.drop_table('books', schema='bible')
    op.drop_index(op.f('ix_versions_youversion_bible_id'), table_name='versions', schema='bible')
    op.drop_index(op.f('ix_versions_language_tag'), table_name='versions', schema='bible')
    op.drop_index(op.f('ix_versions_is_active'), table_name='versions', schema='bible')
    op.drop_table('versions', schema='bible')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS bible")
