"""

Revision ID: cb4541c4145b
Revises: 7cbcd65af3e1
Create Date: 2026-09-06 21:14:20.322375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb4541c4145b'
down_revision: Union[str, Sequence[str], None] = '7cbcd65af3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS push")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('device_key', sa.String(length=255), nullable=False, comment='Client-generated device install key'),
    sa.Column('token', sa.Text(), nullable=False, comment='Current push token (FCM/APNs-via-FCM)'),
    sa.Column('platform', sa.String(length=10), nullable=False, comment='Platform: ios|android'),
    sa.Column('end_user_id', sa.UUID(), nullable=True, comment='FK to app.user.id (End user); null when unauthenticated'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether this device should receive pushes'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time this device registered/refreshed'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='Client app version at last registration'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['end_user_id'], ['app.user.id'], name=op.f('fk_device_end_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('device_key', name=op.f('uq_device_device_key')),
    schema='push',
    comment='Push notification device registrations'
    )
    op.create_index(op.f('ix_device_device_key'), 'device', ['device_key'], unique=False, schema='push')
    op.create_index(op.f('ix_device_end_user_id'), 'device', ['end_user_id'], unique=False, schema='push')
    op.create_table('notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('end_user_id', sa.UUID(), nullable=False, comment='FK to app.user.id (End user)'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='Free-form notification category'),
    sa.Column('title', sa.Text(), nullable=False, comment='Notification title'),
    sa.Column('body', sa.Text(), nullable=False, comment='Notification body'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional structured payload'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.ForeignKeyConstraint(['end_user_id'], ['app.user.id'], name=op.f('fk_notification_end_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification')),
    schema='push',
    comment='Push notifications addressed to an End user'
    )
    op.create_index(op.f('ix_notification_end_user_id'), 'notification', ['end_user_id'], unique=False, schema='push')
    op.create_table('notification_delivery',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('notification_id', sa.UUID(), nullable=False, comment='FK to push.notification.id'),
    sa.Column('device_id', sa.UUID(), nullable=False, comment='FK to push.device.id'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False, comment='Delivery status: pending|success|failed'),
    sa.Column('error', sa.Text(), nullable=True, comment='Failure detail, if any'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='When delivery to this Device succeeded'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.ForeignKeyConstraint(['device_id'], ['push.device.id'], name=op.f('fk_notification_delivery_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['push.notification.id'], name=op.f('fk_notification_delivery_notification_id_notification'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery')),
    sa.UniqueConstraint('notification_id', 'device_id', name=op.f('uq_notification_delivery_notification_id_device_id')),
    schema='push',
    comment='Per-device delivery attempts for a Notification'
    )
    op.create_index(op.f('ix_notification_delivery_device_id'), 'notification_delivery', ['device_id'], unique=False, schema='push')
    op.create_index(op.f('ix_notification_delivery_notification_id'), 'notification_delivery', ['notification_id'], unique=False, schema='push')
    op.create_unique_constraint(op.f('uq_role_permission_role_id_permission_id'), 'role_permission', ['role_id', 'permission_id'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_role_permission_role_id_permission_id'), 'role_permission', schema='auth', type_='unique')
    op.drop_index(op.f('ix_notification_delivery_notification_id'), table_name='notification_delivery', schema='push')
    op.drop_index(op.f('ix_notification_delivery_device_id'), table_name='notification_delivery', schema='push')
    op.drop_table('notification_delivery', schema='push')
    op.drop_index(op.f('ix_notification_end_user_id'), table_name='notification', schema='push')
    op.drop_table('notification', schema='push')
    op.drop_index(op.f('ix_device_end_user_id'), table_name='device', schema='push')
    op.drop_index(op.f('ix_device_device_key'), table_name='device', schema='push')
    op.drop_table('device', schema='push')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS push")
