"""widen book abbreviation

Revision ID: 53f828f0cf4d
Revises: 3a5fb35a2a70
Create Date: 2026-10-01 22:47:35.607742

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53f828f0cf4d'
down_revision: Union[str, Sequence[str], None] = '3a5fb35a2a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'books',
        'abbreviation',
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=50),
        existing_comment='Book abbreviation',
        existing_nullable=True,
        schema='bible',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'books',
        'abbreviation',
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=10),
        existing_comment='Book abbreviation',
        existing_nullable=True,
        schema='bible',
    )
    # ### end Alembic commands ###
