"""drop app user reonboarding

Revision ID: 5ab9e424a1bd
Revises: b9d987b805f3
Create Date: 2026-09-09 23:21:11.463240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ab9e424a1bd'
down_revision: Union[str, Sequence[str], None] = 'b9d987b805f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reonboarding_requested_at', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'reonboarding_requested_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment='When an Admin asked this End user to replay onboarding; cleared once the client acknowledges it',
        ),
        schema='app',
    )
    # ### end Alembic commands ###
