"""add auth credential, identity, and session tables

Revision ID: 1aa874fffc66
Revises: cc1ca267fcb4
Create Date: 2026-09-05 19:39:46.611931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aa874fffc66'
down_revision: Union[str, Sequence[str], None] = 'cc1ca267fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_provider',
    sa.Column('code', sa.String(length=32), nullable=False, comment='Stable provider code, e.g. google, apple'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='English display name'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether provider may be used for new links'),
    sa.Column('requires_tenant', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether provider_tenant is required on Identity links'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_identity_provider')),
    schema='auth'
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email, required unique identifier'),
    sa.Column('password_hash', sa.String(length=512), nullable=True, comment='Password hash; null for passwordless End users'),
    sa.Column('salt', sa.String(length=128), nullable=True, comment='Salt for password hash'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='Is verified'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Is superuser'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Is admin'),
    sa.Column('account_kind', sa.String(length=32), nullable=True, comment='Account kind: member, guest, external, service'),
    sa.Column('password_changed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password last changed time'),
    sa.Column('password_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password expiration time'),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last login'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False, schema='auth')
    op.create_table('device',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='First seen at'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last seen at'),
    sa.Column('last_ip', sa.String(length=45), nullable=True, comment='Last IP'),
    sa.Column('last_user_agent', sa.String(length=512), nullable=True, comment='Last user agent'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_device_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_device_id_user_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False, schema='auth')
    op.create_table('identity_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Auth credential ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='Identity provider code'),
    sa.Column('provider_tenant', sa.String(length=255), nullable=True, comment='Optional provider tenant (string); null for consumer IdPs'),
    sa.Column('provider_subject', sa.String(length=255), nullable=False, comment='Provider subject / stable user id at the IdP'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional IdP snapshot (email, name, auth_time); not the identity key'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['provider'], ['auth.identity_provider.code'], name=op.f('fk_identity_link_provider_identity_provider'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_identity_link_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_link')),
    schema='auth'
    )
    op.create_index(op.f('ix_identity_link_provider'), 'identity_link', ['provider'], unique=False, schema='auth')
    op.create_index(op.f('ix_identity_link_user_id'), 'identity_link', ['user_id'], unique=False, schema='auth')
    op.create_index('uq_identity_link_provider_subject_active', 'identity_link', ['provider', 'provider_tenant', 'provider_subject'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted IS false'), postgresql_nulls_not_distinct=True)
    op.create_index('uq_identity_link_user_provider_active', 'identity_link', ['user_id', 'provider'], unique=True, schema='auth', postgresql_where=sa.text('is_deleted IS false'))
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('first_name', sa.String(length=64), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=64), nullable=False, comment='Last name'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='Title'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='Refer to Gender enum'),
    sa.Column('preferred_name', sa.String(length=64), nullable=True, comment='Preferred name'),
    sa.Column('preferred_locale_id', sa.UUID(), nullable=True, comment='Preferred locale ID'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.ForeignKeyConstraint(['preferred_locale_id'], ['public.system_locale.id'], name=op.f('fk_user_profile_preferred_locale_id_system_locale'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_user_profile_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_profile_preferred_locale_id'), 'user_profile', ['preferred_locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True, schema='auth')
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('device_id', sa.UUID(), nullable=True, comment='Device ID'),
    sa.Column('family_id', sa.UUID(), nullable=False, comment='Family ID'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Parent ID'),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True, comment='Replaced by ID'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='Token hash'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expires at'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last used at'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Revoked at'),
    sa.Column('revoked_reason', sa.String(length=32), nullable=True, comment='Revoked reason'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['device_id'], ['auth.device.id'], name=op.f('fk_refresh_token_device_id_device'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth.refresh_token.id'], name=op.f('fk_refresh_token_parent_id_refresh_token'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['auth.refresh_token.id'], name=op.f('fk_refresh_token_replaced_by_id_refresh_token'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    schema='auth'
    )
    op.create_index(op.f('ix_refresh_token_device_id'), 'refresh_token', ['device_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_expires_at'), 'refresh_token', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_last_used_at'), 'refresh_token', ['last_used_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_parent_id'), 'refresh_token', ['parent_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_replaced_by_id'), 'refresh_token', ['replaced_by_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True, schema='auth')
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_replaced_by_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_parent_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_last_used_at'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_expires_at'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_device_id'), table_name='refresh_token', schema='auth')
    op.drop_table('refresh_token', schema='auth')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile', schema='auth')
    op.drop_index(op.f('ix_user_profile_preferred_locale_id'), table_name='user_profile', schema='auth')
    op.drop_table('user_profile', schema='auth')
    op.drop_index('uq_identity_link_user_provider_active', table_name='identity_link', schema='auth', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('uq_identity_link_provider_subject_active', table_name='identity_link', schema='auth', postgresql_where=sa.text('is_deleted IS false'), postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_identity_link_user_id'), table_name='identity_link', schema='auth')
    op.drop_index(op.f('ix_identity_link_provider'), table_name='identity_link', schema='auth')
    op.drop_table('identity_link', schema='auth')
    op.drop_index(op.f('ix_device_user_id'), table_name='device', schema='auth')
    op.drop_table('device', schema='auth')
    op.drop_index(op.f('ix_user_is_active'), table_name='user', schema='auth')
    op.drop_table('user', schema='auth')
    op.drop_table('identity_provider', schema='auth')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS auth")
