"""add app end user and preferences tables

Revision ID: 801343331fc0
Revises: f5cbb4c9a264
Create Date: 2026-09-05 19:49:24.231423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801343331fc0'
down_revision: Union[str, Sequence[str], None] = 'f5cbb4c9a264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('auth_user_id', sa.UUID(), nullable=False, comment='Shared credential FK to auth.user (IDs are not shared)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth.user.id'], name=op.f('fk_user_auth_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('auth_user_id', name=op.f('uq_user_auth_user_id')),
    schema='app',
    comment='End user identity (app.user). Future product FKs target this id, not auth.user.id (ADR 0004).'
    )
    op.create_index(op.f('ix_user_auth_user_id'), 'user', ['auth_user_id'], unique=False, schema='app')
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK to app.user.id (End user)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Display name'),
    sa.Column('locale', sa.String(length=10), server_default='zh-Hant', nullable=False, comment='Locale tag'),
    sa.Column('theme', sa.String(length=10), server_default='system', nullable=False, comment='Theme: light|dark|system'),
    sa.Column('font_scale', sa.String(length=2), server_default='M', nullable=False, comment='Font scale: S|M|L'),
    sa.Column('bible_version', sa.String(length=20), server_default='cuv1919', nullable=False, comment='Soft bible version key (not a hard FK)'),
    sa.Column('stage', sa.String(length=20), nullable=True, comment='Stage: seeking|growing|serving'),
    sa.Column('reminder_time', sa.Time(), nullable=True, comment='Daily reminder time'),
    sa.Column('reminder_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether reminder is enabled'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], name=op.f('fk_user_preferences_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id')),
    schema='app',
    comment='End user Preferences 1:1 with app.user (not auth.user_profile)'
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences', schema='app')
    op.drop_table('user_preferences', schema='app')
    op.drop_index(op.f('ix_user_auth_user_id'), table_name='user', schema='app')
    op.drop_table('user', schema='app')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS app")
