"""add lesson notes

Revision ID: b9d987b805f3
Revises: 4a2cf18c310c
Create Date: 2026-09-09 12:48:03.871640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d987b805f3'
down_revision: Union[str, Sequence[str], None] = '4a2cf18c310c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reflect_answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Ordered optional reflection answers'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], name=op.f('fk_lesson_notes_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_notes')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_lesson_notes_user_id_date')),
    schema='devotion',
    comment='One private lesson note per End user and date'
    )
    op.create_index(op.f('ix_lesson_notes_date'), 'lesson_notes', ['date'], unique=False, schema='devotion')
    op.create_index(op.f('ix_lesson_notes_user_id'), 'lesson_notes', ['user_id'], unique=False, schema='devotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_notes_user_id'), table_name='lesson_notes', schema='devotion')
    op.drop_index(op.f('ix_lesson_notes_date'), table_name='lesson_notes', schema='devotion')
    op.drop_table('lesson_notes', schema='devotion')
    # ### end Alembic commands ###
