"""add audit log table

Revision ID: 7b2ae7063695
Revises: 575ca558fe89
Create Date: 2026-09-05 19:47:44.899822

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b2ae7063695'
down_revision: Union[str, Sequence[str], None] = '575ca558fe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'log',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('record_id', sa.UUID(), nullable=True, comment='Record ID in the audited table'),
        sa.Column(
            'operation_type',
            sa.String(length=32),
            nullable=False,
            comment='Operation type string (OperationType.value). refer to libs.consts.enums.OperationType',
        ),
        sa.Column('operation_code', sa.String(length=64), nullable=True, comment='Operation code(default use table name)'),
        sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete old record data'),
        sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete new record data'),
        sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Only the fields that changed with old/new values'),
        sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
        sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent string'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_log')),
        schema='audit',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log', schema='audit')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS audit")
