"""add content file and legal document tables

Revision ID: f5cbb4c9a264
Revises: 7b2ae7063695
Create Date: 2026-09-05 19:48:12.944476

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5cbb4c9a264'
down_revision: Union[str, Sequence[str], None] = '7b2ae7063695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS content")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'file',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename as uploaded'),
        sa.Column('key', sa.String(length=512), nullable=False, comment='Storage object key (path)'),
        sa.Column('storage', sa.String(length=16), nullable=False, comment='Storage backend, e.g., azure_blob, s3'),
        sa.Column('bucket', sa.String(length=128), nullable=False, comment='Container or bucket name'),
        sa.Column('region', sa.String(length=32), nullable=False, comment='Storage region'),
        sa.Column('content_type', sa.String(length=128), nullable=True, comment='MIME type'),
        sa.Column('extension', sa.String(length=16), nullable=True, comment='File extension'),
        sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='File size in bytes'),
        sa.Column('checksum_md5', sa.String(length=32), nullable=True, comment='MD5 checksum'),
        sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='SHA-256 checksum'),
        sa.Column('width', sa.Integer(), nullable=True, comment='Image width in pixels'),
        sa.Column('height', sa.Integer(), nullable=True, comment='Image height in pixels'),
        sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Media duration in seconds'),
        sa.Column('status', sa.Integer(), nullable=False, comment='File status, refer to FileStatus enum'),
        sa.Column('version', sa.Integer(), nullable=False, comment='File version number'),
        sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether the file is public'),
        sa.Column('source', sa.Integer(), nullable=True, comment='Upload source, refer to FileUploadSource'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_file')),
        sa.UniqueConstraint('bucket', 'key', name=op.f('uq_file_bucket_key')),
        schema='content',
    )
    op.create_index(op.f('ix_file_key'), 'file', ['key'], unique=False, schema='content')
    op.create_table(
        'legal_document',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('product', sa.String(length=64), nullable=False, comment='Built-in Product code'),
        sa.Column('kind', sa.String(length=64), nullable=False, comment='Legal Document Kind'),
        sa.Column('effective_date', sa.Date(), nullable=False, comment='Calendar day when current wording takes effect'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_document')),
        sa.UniqueConstraint('product', 'kind', name=op.f('uq_legal_document_product_kind')),
        schema='content',
    )
    op.create_index('ix_legal_document_product_kind_deleted', 'legal_document', ['product', 'kind', 'is_deleted'], unique=False, schema='content')
    op.create_table(
        'file_association',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('file_id', sa.UUID(), nullable=False, comment='File ID'),
        sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
        sa.Column('resource_name', sa.String(length=32), nullable=False, comment='Resource name (default table name)'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp',
        ),
        sa.ForeignKeyConstraint(['file_id'], ['content.file.id'], name=op.f('fk_file_association_file_id_file'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_file_association')),
        schema='content',
    )
    op.create_index(op.f('ix_file_association_file_id'), 'file_association', ['file_id'], unique=False, schema='content')
    op.create_index(op.f('ix_file_association_resource_id'), 'file_association', ['resource_id'], unique=False, schema='content')
    op.create_index(op.f('ix_file_association_resource_name'), 'file_association', ['resource_name'], unique=False, schema='content')
    op.create_table(
        'legal_document_translation',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('legal_document_id', sa.UUID(), nullable=False, comment='Legal Document ID'),
        sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
        sa.Column('body', sa.Text(), server_default=sa.text("''"), nullable=False, comment='Markdown body'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.ForeignKeyConstraint(
            ['legal_document_id'],
            ['content.legal_document.id'],
            name=op.f('fk_legal_document_translation_legal_document_id_legal_document'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['locale_id'], ['public.system_locale.id'], name=op.f('fk_legal_document_translation_locale_id_system_locale'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_document_translation')),
        sa.UniqueConstraint('legal_document_id', 'locale_id', name=op.f('uq_legal_document_translation_legal_document_id_locale_id')),
        schema='content',
    )
    op.create_index(
        op.f('ix_legal_document_translation_legal_document_id'), 'legal_document_translation', ['legal_document_id'], unique=False, schema='content'
    )
    op.create_index(op.f('ix_legal_document_translation_locale_id'), 'legal_document_translation', ['locale_id'], unique=False, schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_document_translation_locale_id'), table_name='legal_document_translation', schema='content')
    op.drop_index(op.f('ix_legal_document_translation_legal_document_id'), table_name='legal_document_translation', schema='content')
    op.drop_table('legal_document_translation', schema='content')
    op.drop_index(op.f('ix_file_association_resource_name'), table_name='file_association', schema='content')
    op.drop_index(op.f('ix_file_association_resource_id'), table_name='file_association', schema='content')
    op.drop_index(op.f('ix_file_association_file_id'), table_name='file_association', schema='content')
    op.drop_table('file_association', schema='content')
    op.drop_index('ix_legal_document_product_kind_deleted', table_name='legal_document', schema='content')
    op.drop_table('legal_document', schema='content')
    op.drop_index(op.f('ix_file_key'), table_name='file', schema='content')
    op.drop_table('file', schema='content')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS content")
