"""add system locale and setting tables

Revision ID: cc1ca267fcb4
Revises: 
Create Date: 2026-09-05 19:37:26.096213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1ca267fcb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_locale',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('language_code', sa.String(length=16), nullable=False, comment='Language code (e.g., en, zh, etc.)'),
    sa.Column('script_code', sa.String(length=16), nullable=True, comment='Script code (e.g., Latn, Hant, etc.)'),
    sa.Column('region_code', sa.String(length=16), nullable=True, comment='Region code (e.g., US, TW, etc.)'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Locale name'),
    sa.Column('native_name', sa.String(length=64), nullable=True, comment='Native locale name'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is locale active'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='Is default locale'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_locale')),
    sa.UniqueConstraint('language_code', 'script_code', 'region_code', name=op.f('uq_system_locale_language_code_script_code_region_code')),
    schema='public'
    )
    op.create_table('system_setting',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('namespace', sa.String(length=64), nullable=False, comment='Setting namespace'),
    sa.Column('setting_key', sa.String(length=64), nullable=False, comment='Setting key within namespace'),
    sa.Column('value_type', sa.String(length=32), nullable=False, comment='Declared value type (SettingValueType)'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON value matching value_type'),
    sa.Column('is_built_in', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Built-in settings cannot be deleted'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_setting')),
    sa.UniqueConstraint('namespace', 'setting_key', name=op.f('uq_system_setting_namespace_setting_key')),
    schema='public'
    )
    op.create_index(op.f('ix_system_setting_is_active'), 'system_setting', ['is_active'], unique=False, schema='public')
    op.create_index('ix_system_setting_namespace_key_active', 'system_setting', ['namespace', 'setting_key', 'is_active'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_setting_namespace_key_active', table_name='system_setting', schema='public')
    op.drop_index(op.f('ix_system_setting_is_active'), table_name='system_setting', schema='public')
    op.drop_table('system_setting', schema='public')
    op.drop_table('system_locale', schema='public')
    # ### end Alembic commands ###
