"""add auth RBAC roles, resources, verbs, and permissions

Revision ID: 575ca558fe89
Revises: 1aa874fffc66
Create Date: 2026-09-05 19:45:51.371271

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '575ca558fe89'
down_revision: Union[str, Sequence[str], None] = '1aa874fffc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resource',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('pid', sa.UUID(), nullable=True, comment='Parent resource id'),
        sa.Column('key', sa.String(length=128), nullable=False, comment='Resource key and front-end corresponding'),
        sa.Column('code', sa.String(length=32), nullable=False, comment='Resource code (e.g., user, course, article)'),
        sa.Column('icon', sa.String(length=32), nullable=True, comment='Resource icon'),
        sa.Column('path', sa.String(length=256), nullable=True, comment='Resource path'),
        sa.Column('type', sa.Integer(), nullable=False, comment='Resource type, Enum: ResourceType'),
        sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Is resource visible'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp',
        ),
        sa.ForeignKeyConstraint(['pid'], ['auth.resource.id'], name=op.f('fk_resource_pid_resource'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_resource')),
        sa.UniqueConstraint('code', name=op.f('uq_resource_code')),
        sa.UniqueConstraint('key', name=op.f('uq_resource_key')),
        schema='auth',
    )
    op.create_table(
        'role',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('code', sa.String(length=32), nullable=False, comment='Role code'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is role active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
        sa.UniqueConstraint('code', name=op.f('uq_role_code')),
        schema='auth',
    )
    op.create_table(
        'verb',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('action', sa.String(length=32), nullable=False, comment='Verb action (e.g., create, read, update, delete)'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is verb active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_verb')),
        sa.UniqueConstraint('action', name=op.f('uq_verb_action')),
        schema='auth',
    )
    op.create_table(
        'permission',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
        sa.Column('verb_id', sa.UUID(), nullable=False, comment='Verb ID'),
        sa.Column('code', sa.String(length=128), nullable=False, comment='Permission Code (e.g., user:read)'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is permission active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.ForeignKeyConstraint(['resource_id'], ['auth.resource.id'], name=op.f('fk_permission_resource_id_resource'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['verb_id'], ['auth.verb.id'], name=op.f('fk_permission_verb_id_verb'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
        sa.UniqueConstraint('code', name=op.f('uq_permission_code')),
        sa.UniqueConstraint('resource_id', 'verb_id', name=op.f('uq_permission_resource_id_verb_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_permission_resource_id'), 'permission', ['resource_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_permission_verb_id'), 'permission', ['verb_id'], unique=False, schema='auth')
    op.create_table(
        'resource_translation',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
        sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='Resource name'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_resource_translation_locale_id_system_locale'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['resource_id'], ['auth.resource.id'], name=op.f('fk_resource_translation_resource_id_resource'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_translation')),
        sa.UniqueConstraint('resource_id', 'locale_id', name=op.f('uq_resource_translation_resource_id_locale_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_resource_translation_locale_id'), 'resource_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_resource_translation_resource_id'), 'resource_translation', ['resource_id'], unique=False, schema='auth')
    op.create_table(
        'role_translation',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
        sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='Role name'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_role_translation_locale_id_system_locale'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_role_translation_role_id_role'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_role_translation')),
        sa.UniqueConstraint('role_id', 'locale_id', name=op.f('uq_role_translation_role_id_locale_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_role_translation_locale_id'), 'role_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_translation_role_id'), 'role_translation', ['role_id'], unique=False, schema='auth')
    op.create_table(
        'user_role',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_user_role_role_id_role'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_user_role_user_id_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role')),
        schema='auth',
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False, schema='auth')
    op.create_table(
        'verb_translation',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('verb_id', sa.UUID(), nullable=False, comment='Verb ID'),
        sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='Verb name'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_verb_translation_locale_id_system_locale'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['verb_id'], ['auth.verb.id'], name=op.f('fk_verb_translation_verb_id_verb'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_verb_translation')),
        sa.UniqueConstraint('verb_id', 'locale_id', name=op.f('uq_verb_translation_verb_id_locale_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_verb_translation_locale_id'), 'verb_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_verb_translation_verb_id'), 'verb_translation', ['verb_id'], unique=False, schema='auth')
    op.create_table(
        'permission_translation',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
        sa.Column('permission_id', sa.UUID(), nullable=False, comment='Permission ID'),
        sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
        sa.Column('name', sa.String(length=128), nullable=False, comment='Permission name'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_permission_translation_locale_id_system_locale'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['permission_id'], ['auth.permission.id'], name=op.f('fk_permission_translation_permission_id_permission'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_translation')),
        sa.UniqueConstraint('permission_id', 'locale_id', name=op.f('uq_permission_translation_permission_id_locale_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_permission_translation_locale_id'), 'permission_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_permission_translation_permission_id'), 'permission_translation', ['permission_id'], unique=False, schema='auth')
    op.create_table(
        'role_permission',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='Expiration time, can be used for temporary authorization'),
        sa.ForeignKeyConstraint(['permission_id'], ['auth.permission.id'], name=op.f('fk_role_permission_permission_id_permission'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission')),
        sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permission_role_id_permission_id')),
        schema='auth',
    )
    op.create_index(op.f('ix_role_permission_expire_date'), 'role_permission', ['expire_date'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission', schema='auth')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission', schema='auth')
    op.drop_index(op.f('ix_role_permission_expire_date'), table_name='role_permission', schema='auth')
    op.drop_table('role_permission', schema='auth')
    op.drop_index(op.f('ix_permission_translation_permission_id'), table_name='permission_translation', schema='auth')
    op.drop_index(op.f('ix_permission_translation_locale_id'), table_name='permission_translation', schema='auth')
    op.drop_table('permission_translation', schema='auth')
    op.drop_index(op.f('ix_verb_translation_verb_id'), table_name='verb_translation', schema='auth')
    op.drop_index(op.f('ix_verb_translation_locale_id'), table_name='verb_translation', schema='auth')
    op.drop_table('verb_translation', schema='auth')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role', schema='auth')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role', schema='auth')
    op.drop_table('user_role', schema='auth')
    op.drop_index(op.f('ix_role_translation_role_id'), table_name='role_translation', schema='auth')
    op.drop_index(op.f('ix_role_translation_locale_id'), table_name='role_translation', schema='auth')
    op.drop_table('role_translation', schema='auth')
    op.drop_index(op.f('ix_resource_translation_resource_id'), table_name='resource_translation', schema='auth')
    op.drop_index(op.f('ix_resource_translation_locale_id'), table_name='resource_translation', schema='auth')
    op.drop_table('resource_translation', schema='auth')
    op.drop_index(op.f('ix_permission_verb_id'), table_name='permission', schema='auth')
    op.drop_index(op.f('ix_permission_resource_id'), table_name='permission', schema='auth')
    op.drop_table('permission', schema='auth')
    op.drop_table('verb', schema='auth')
    op.drop_table('role', schema='auth')
    op.drop_table('resource', schema='auth')
    # ### end Alembic commands ###
